# Generated by Django 5.0.6 on 2024-10-07 02:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=50, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('job', models.CharField(max_length=200, verbose_name='Режим работы')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
    ]
