# Generated by Django 5.0.6 on 2024-10-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
