# Generated by Django 5.0.6 on 2024-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(default=1, upload_to='', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
