# Generated by Django 5.0.6 on 2024-10-06 23:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
