# Generated by Django 5.0.6 on 2024-10-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_is_popular_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='from_city',
            new_name='city',
        ),
    ]
