# Generated by Django 5.0.6 on 2024-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_from_city_hotel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.ImageField(upload_to='', verbose_name='Иконка для "Город"')),
                ('location_text', models.CharField(default='Находится в центре', max_length=30, verbose_name='Находится в центре')),
                ('icon_location', models.ImageField(upload_to='', verbose_name='Иконка для "Местоположения(Находится в центре)"')),
            ],
            options={
                'verbose_name': 'Иконка после названия',
                'verbose_name_plural': 'Иконки после названия',
            },
        ),
    ]
