# Generated by Django 5.0.6 on 2024-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestChoices',
        ),
        migrations.DeleteModel(
            name='RestIdeas',
        ),
        migrations.AddField(
            model_name='tour',
            name='is_best_choice',
            field=models.BooleanField(default=False, verbose_name='Лучшее предложение'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_rest_idea',
            field=models.BooleanField(default=False, verbose_name='Идея для отдыха'),
        ),
    ]
