# Generated by Django 5.0.6 on 2024-10-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_delete_bestchoices_delete_restideas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.ImageField(upload_to='', verbose_name='Иконка для "Город/Страна"')),
                ('icon_date', models.ImageField(upload_to='', verbose_name='Иконка для даты "Туда/Обратно"')),
            ],
        ),
    ]
