# Generated by Django 5.0.6 on 2024-10-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_iconsaftername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconsaftername',
            options={'verbose_name': 'Иконка после названия', 'verbose_name_plural': 'Иконки после названия'},
        ),
    ]
