# Generated by Django 5.0.6 on 2024-10-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order']},
        ),
    ]
