# Generated by Django 5.0.6 on 2024-10-07 00:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Содержимое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='second_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_section_images/', verbose_name='Картинка'),
        ),
    ]
