# Generated by Django 5.0.6 on 2024-10-07 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_content_blogpost_second_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order'], 'verbose_name': 'Детальная страница', 'verbose_name_plural': 'Детальные страницы'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='second_title',
            field=models.CharField(max_length=200, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
