# Generated by Django 5.0.6 on 2024-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_iconsaftername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconsaftername',
            name='icon_city_country',
            field=models.ImageField(upload_to='', verbose_name='Иконка для "Откуда/Куда"'),
        ),
    ]
