# Generated by Django 5.0.6 on 2024-10-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.ManyToManyField(related_name='best_choices', to='tours.tour', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Лучшее предложение',
                'verbose_name_plural': 'Лучшие предложения',
            },
        ),
        migrations.CreateModel(
            name='PopularHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', models.ManyToManyField(related_name='popular_hotels', to='hotels.hotel', verbose_name='Отели')),
            ],
            options={
                'verbose_name': 'Популярный отель',
                'verbose_name_plural': 'Популярные отели',
            },
        ),
        migrations.CreateModel(
            name='RestIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.ManyToManyField(related_name='rest_ideas', to='tours.tour', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Идея для отдыха',
                'verbose_name_plural': 'Идеи для отдыха',
            },
        ),
    ]
