# Generated by Django 5.0.6 on 2024-10-06 23:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rentofcar',
            name='title',
            field=models.CharField(default='Аренда автомобиля', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rentofcardescription',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
