# Generated by Django 5.0.6 on 2024-10-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rentofcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentofcar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rentofcar',
            name='image',
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='description1',
            field=models.TextField(default=1, verbose_name='Описание 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='description2',
            field=models.TextField(default=1, verbose_name='Описание 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='description3',
            field=models.TextField(default=1, verbose_name='Описание 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='description4',
            field=models.TextField(default=1, verbose_name='Описание 4'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RentOfCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_rentals/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('rent_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.rentofcar', verbose_name='Аренда автомобиля')),
            ],
            options={
                'verbose_name': 'Изображение аренды автомобиля',
                'verbose_name_plural': 'Изображения аренды автомобилей',
                'ordering': ['order'],
            },
        ),
    ]
