# Generated by Django 5.0.6 on 2024-10-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rentofcar_description_remove_rentofcar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentofcar',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='rentofcar',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='rentofcar',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='rentofcar',
            name='description4',
        ),
        migrations.CreateModel(
            name='RentOfCarDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('rent_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.rentofcar', verbose_name='Аренда автомобиля')),
            ],
            options={
                'verbose_name': 'Описание аренды автомобиля',
                'verbose_name_plural': 'Описания аренды автомобилей',
                'ordering': ['order'],
            },
        ),
    ]
