# Generated by Django 5.0.6 on 2024-10-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_rentofcar_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentofcar',
            name='price',
        ),
    ]
