# Generated by Django 5.0.6 on 2024-10-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_benefits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Преимущество работы с нами', 'verbose_name_plural': 'Преимущества работы с нами'},
        ),
    ]
