# Generated by Django 5.0.6 on 2024-10-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_tag_icon'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_city',
        ),
        migrations.AddField(
            model_name='transfer',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_city', to='common.city', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
