# Generated by Django 5.0.6 on 2024-10-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши Проекты', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('youtube_video_url', models.URLField(verbose_name='URL видео с YouTube')),
            ],
            options={
                'verbose_name': 'Наши проекты',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
