# Generated by Django 5.0.6 on 2024-10-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_ourprojects'),
        ('tours', '0002_delete_bestchoices_delete_restideas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='tours',
            field=models.ManyToManyField(related_name='our_projects', to='tours.tour', verbose_name='Связанные туры'),
        ),
    ]
